mozilla/mp4parse-rust

src/capi.rs

We expect to hit EOF normally when parsing most mp4 fragments,
so handle this as a recoverable error.

Don't poison the demuxer context on EOF.

---

src/lib.rs

Implement `Default` for some types and add some ticks to documentation.

Default impls and documentation ticks.

---

Cargo.toml
src/lib.rs

Set some structs/fields public

---

src/lib.rs
tests/public.rs

Add test to keep needed fields public

---

mp4parse_capi/src/lib.rs

This modifies mp4parse_get_track_info to match libstagefright's behaviour more closely, where unknown durations are returned as zero.
Discovered with the media.rust.test_mode pref enabled while browsing macworld.com (specifically http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html, which plays a random video thumbnail in the top left).
I've saved a copy of the `moov` chunk from the testcase.  For future reference, the "easy" way to do this once an MP4Metadata.cpp mismatch assert fires is (in gdb):
`dump memory testcase.mp4 (uint8_t*)(mRustSource.mSource->mData->mHdr+1) (uint8_t*)(mRustSource.mSource->mData->mHdr+1) + mRustSource.mSource->mData->mHdr.mLength`

Use zero for unknown track durations rather than returning an error.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

FLACSpecificBox is now a fullbox.

Update flac parser for the 0.0.2 draft specification.

---

mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/src/lib.rs

Copy avc extra data to gecko.
https://bugzilla.mozilla.org/show_bug.cgi?id=1317609

Set avc extra_data

---

mp4parse/Cargo.toml

Hi! [crates.io now supports categories][categories], which are a curated list
of topics aimed at helping an end-user coming to crates.io looking for
"a crate to do ______".
We're sending pull requests to selected crates to add categories in order to help 
populate the categories and seed their usefulness. We've made a guess at the best
category/categories for this crate; if it doesn't fit, please feel free to take
a look at [all the available categories and their descriptions][categories] and
[the slug values that should be specified in your Cargo.toml][slugs] and pick
different ones. If you have a category in mind that isn't available, you can
[send a PR to this file on crates.io][categories.toml] to propose additional
categories.
Crates can have up to 5 categories, and uploading …

Add categories to Cargo.toml

---

mp4parse_capi/src/lib.rs

Chunk number in ```stsc``` could be different to ```stco```. Because the last few chunks in ```stco``` could belong to the last record of ```stsc```, so we need to check the remain chunk number in the last range of ```stsc```.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1340447

check chunk number in stsc iterator

---

mp4parse/src/boxes.rs
mp4parse_capi/src/lib.rs

Address more clippy warnings

---

mp4parse_capi/Cargo.toml
mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs

Move to our published fork of rusty-cheddar instead of
building against a git repo.

Migrate to moz-cheddar 0.4.0.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

This is for https://github.com/mozilla/mp4parse-rust/issues/90.
Optional extended descriptor type tag size is one byte in this case, not three. Instead of always checking three bytes, this PR checks the extension descriptor tag from one up to three bytes to handle this case.

fix for one byte extend descriptor tag

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

Update vpcc parsing to 'VP Codec ISO Media File Format' version 1

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

Limited the table length in case of OOM by malicious content.
https://bugzilla.mozilla.org/show_bug.cgi?id=1367508

limited table size in case of OOM

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

We should return unknown codec box instead of error, to be exact, not a parsing error.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1378607

returning unknown codec box instead of error

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

Closed https://github.com/mozilla/mp4parse-rust/pull/102 by accident. Recreate a new one.

Return unknown for unsupported codec

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1388618
Invalid ```pssh``` header size causes OOM.

check PSSH header length before calling Vec::with_capacity

---

mp4parse_capi/src/lib.rs

Subtraction underflow. I'll add a testcase in gecko part.
https://bugzilla.mozilla.org/show_bug.cgi?id=1389527

use checked_sub to avoid underflow

---

mp4parse_capi/examples/dump.rs
mp4parse_capi/src/lib.rs

Dump structures from all APIs in mp4parse_capi to debug easily.

Dump data from mp4parse_capi API

---

mp4parse_capi/src/lib.rs

It is from https://bugzilla.mozilla.org/show_bug.cgi?id=1388991.
I'll add a test case in gecko gtest later.

check subtraction underflow

---

mp4parse_capi/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1407833

check add overflow

---

mp4parse/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1422684

fix a typo in frequency table

---

.travis.yml
Cargo.toml
mp4parse_capi/examples/Makefile

Build with --release on Travis.

---

mp4parse/src/lib.rs
mp4parse_capi/examples/test.cc

This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1609573
r? @SingingTree please

Bump BUF_SIZE_LIMIT to 10MB

---

mp4parse/src/lib.rs
mp4parse_capi/examples/dump.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_chunk_out_of_range.rs
mp4parse_capi/tests/test_encryption.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs
mp4parse_capi/tests/test_workaround_stsc.rs

See https://github.com/mozilla/mp4parse-rust/issues/195 and individual commit messages

Merge mp4parse[_avif]_read into mp4parse[_avif]_new

---

.travis.yml

There may be a cleaner way to do this with https://docs.travis-ci.com/user/conditions-v1, but I wasn't really sure, and I'm fairly confident this will do what we need.

Don't run rustfmt check in nightly; fix bug

---

mp4parse/Cargo.toml
mp4parse/tests/public.rs

Also update test code to recurse testFiles directory so adding new test images
doesn't require code changes in the future.

Update submodule to pull in AVIF test images from Link-U

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_encryption.rs

Fixes https://github.com/mozilla/mp4parse-rust/issues/218.

Expose encrypted original format via C API

---

mp4parse/src/lib.rs
mp4parse_capi/examples/dump.rs

See https://bugzilla.mozilla.org/show_bug.cgi?id=1641972

Miscellaneous fixes related to bug investigation

---

mp4parse_capi/fuzz/Cargo.toml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1657244

Always enable fallible allocation for fuzz targets

---

mp4parse/src/lib.rs

See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22366

Return an error if there are multiple decoder-specific descriptors

---

mp4parse/src/lib.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/examples/dump.rs
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_sample_table.rs

Hopefully this should catch all the potential fuzzing crashes due to overflow.
And a few little clippy fixes.

Add a CheckedInteger type to ensure checked arithmetic

---

mp4parse/Cargo.toml
mp4parse/src/boxes.rs
mp4parse/src/lib.rs

This PR contains various cleanups that shouldn't change behavior in any meaningful way. The different kinds are separated by commit for ease of review.

Misc cleanup

---

mp4parse_capi/src/lib.rs

This fixes the failure here: https://travis-ci.org/github/mozilla/mp4parse-rust/jobs/748610958#L725 in Rust Nightly.

Fix doctest failure

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

Add myself to authors while I'm tinkering with other changes.

Add Bryce Seager van Dyk to authors.

---

mp4parse_capi/fuzz/Cargo.toml

See https://github.com/google/oss-fuzz/issues/5572

Bump libfuzzer-sys dependency to 0.4.0

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/src/unstable.rs

Addresses https://github.com/mozilla/mp4parse-rust/issues/310

Remove `TABLE_SIZE_LIMIT` and `BUF_SIZE_LIMIT`

---

.github/workflows/build.yml
mp4parse/src/tests.rs
mp4parse/tests/public.rs

Additionally, fix all the lints, obviating https://github.com/mozilla/mp4parse-rust/pull/316

Run clippy CI on all code, including tests

---

.github/workflows/build.yml

This should be a low-cost way to identify easily-fixed issues in code that will be missed by standard CI run against only default features

Add clippy run with all features enabled

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse_capi/cbindgen.toml
mp4parse_capi/src/lib.rs

See https://bugzilla.mozilla.org/show_bug.cgi?id=1634741
Also misc fixups, mostly clippy lints

ColourInformationBox (colr) support

---

mp4parse/tests/public.rs

Not sure how this passed the test run for https://github.com/mozilla/mp4parse-rust/runs/3267258755 considering https://github.com/mozilla/mp4parse-rust/runs/3355854095 failed

Fix test for running with missing-pixi-permitted feature

---

mp4parse/src/lib.rs

See https://github.com/mozilla/mp4parse-rust/issues/340

Add annotations to allow fields which are never read

---

mp4parse/src/lib.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#needless_late_init

Fix clippy::needless-late-init

---

README.md

Previously approved in https://github.com/mozilla/mp4parse-rust/pull/347 with minor revisions

Add Versioning section to README.md

---

mp4parse/src/lib.rs

Resolves https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42726

Preallocate stsd space

---

mp4parse/src/lib.rs

See https://oss-fuzz.com/testcase-detail/4609562076905472

Reserve space in pssh to avoid timeout

---

mp4parse/src/lib.rs

Resolves https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42930
Also, add some additional debugging statements I expect to to be useful in similar fuzzing issues

Only read stsd entries up to `description_count`

---

mp4parse/src/lib.rs

Resolves https://github.com/mozilla/mp4parse-rust/issues/354
Resolves https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42772

`ItemDataBox` support

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

This should've been a part of 98b2e8b, but was overlooked

Update version 0.13.0 -> 0.14.0 due to breaking API changes

---

mp4parse/src/lib.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow

clippy: Remove unnecessary borrow

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/src/macros.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml

This PR is probably best viewed commit-by-commit since there is a lot of moving things around. Individual commit messages should be explanatory.

Replace `Error::InvalidData` with `Error::InvalidDataDetail` and misc cleanups

---

mp4parse/Cargo.toml
mp4parse/src/unstable.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_sample_table.rs

Expose time in ticks relative to a timebase and not in microseconds
