mozilla/mp4parse-rust

src/capi.rs

Sorry, caught this when testing a fresh Gecko build.

Remove MediaContext tracing via C API enabled during debugging.

---

src/capi.rs

mp4parse_get_track_info expected empty_duration and media_time to be
set, but these are extracted from the (optional) edit list.  Remove the
requirement for these to be present and calculate the media start time
as 0 in such cases.

Don't treat tracks without an edit list as invalid.

---

src/lib.rs

The unwrap calls are pre-checked and safe, but they're also unnecessary.

Remove unwrap calls in description parsing.

---

src/capi.rs
src/lib.rs
src/tests.rs

As part of making some things public, move capi-only helpers into capi.rs.

Regularize capi functions

---

mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Since movie and track durations and media times can be 64-bit
integers, converting them to microseconds can overflow. Fortunately
our runtime error checking caught an instance of this.
Change the return type of the conversion routines to an Option and
use checked artimetic. In get_track_info default to 0 for overflowing
media_time and return an error for overflowing duration. This is
sufficient to accept the triggering content.
Rename time_to_ms to time_to_us to clarify that they return times
in microseconds.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1301065

Use checked arithmetic in time_to_us.

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Parse fragment_duration for https://bugzilla.mozilla.org/show_bug.cgi?id=1304254.
Test will be added in another PR later.

Parse mvex to retrieve fragment_duration.

---

mp4parse/src/lib.rs

This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1306236.
Some contents may have extra padding data in the boxes of stbl. For example, stsc, stsz, stsd...etc.
This patch skips these paddings so parser keeps parsing the file.

Skip padding data

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

Basic support for the proposed FLAC encapsulation.

Basic flac support

---

mp4parse/src/lib.rs

This is more consistent than doing our own break-out.

Implement be_u24 in terms of BigEndian::read_uint().

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs

Parse quicktime audio sample entry format.
Quicktime uses a 'wave' atom in audio sample entry box. For 'mp4a', its
'esds' is inside 'wave' atom. That is:
mp4a {
|--- wave {
|------- esds {
|------- }
|--- }
}
Detail spec can be found at: http://multimedia.cx/mirror/qtff-2007-09-04.pdf
Patch summaries:
1. rename read_audio_desc() and read_video_desc() to read_audio_sample_entry() and read_video_sample_entry().
2. move esds codes to function read_esds().
3. add read_qt_wave_atom() to parse qt wave atom.
4. check qt version in read_audio_sample_entry().
I think we also need to parse QT video sample entry? Maybe later.
https://bugzilla.mozilla.org/show_bug.cgi?id=1307045

Parse quicktime audio sample entry

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

Structure of ESDS:
ESDS box
|
|- ES descriptor
|   |- 3 bytes extension (optional)
|   |- 1 byte length
|   |- 2 bytes ES ID
|   |- 1 byte stream priority and flags
|   |- stream dependency (optional, depends on flags)
|   |   |- 2 bytes
|   |- url (optional, depends on flags)
|   |   |- 1 byte length
|   |   |- x bytes, x is the length
|   |
|   |- Decoder Config descriptior
|   |- 3 bytes extension (optional)
|   |- 1 byte length
|   |- 1 byte object profile indicator
We need to get object profile indicator for the codec type.

Parse ESDS.

---

mp4parse/src/lib.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs

Audio channel count in ESDS is different comparing to AudioSampleEntry for Facebook video. Stagefright uses audio channel count from ESDS.
So MP4 rust parser should be able to retrieve it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1311929

check channelcounts in CSD

---

mp4parse/src/tests.rs

These are equivalent, and panic!() is shorter. It's perfectly
fine to use panic! in tests.

Replace assert!(false, ...) pattern with panic!().

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/src/lib.rs

Completed mechanically via `find -name *.rs -type f | xargs untry`.
questionmark became stable in Rust 1.13.0, so merging this PR will make that the minimum version required to build mp4parse-rust.

Convert all instances of try!() to ?.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse_capi/src/lib.rs

The old read_esds() is too long. It is hard to maintain. So I think it'd be better to separate it into small functions.

Separate read_esds() into smaller functions.

---

mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

According  to spec 14496-12, it could be multiple sinf boxes in stream. And I found this case exists in [1] and [2].
And tenc box is optional, sinf doesn't always contain tenc which case found in [1] and [2].
[1] http://shaka-player-demo.appspot.com/demo/  (car clear key)
[2] https://www.netflix.com

Support multiple sinf boxes

---

mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

For http://searchfox.org/mozilla-central/rev/594937fec2e2fc45fa9308ba2fb964816631f017/dom/media/MediaInfo.h#388
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1323390

parse audio object type in esds

---

mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs

mp4parser_capi acts as the bridge between rust and gecko. So the structures from gecko need to be initialized to default value in case of unused members.

Initialize structures

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs

1. use bit-reader to rewrite read_ds_descriptor() for better bit reading.
2. check extended field.

Refactor read_ds_descriptor() with bitreader

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/src/tests.rs

This is from [1]. The audio channel count is zero in decoder config descriptor, so we need to calculate the channel count from program_config_element [2].
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1328221
[2] 14496-3  4.4.1 Decoder configuration (GASpecificConfig)

parse program_config_element for channel counts

---

mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

This is the first PR for sample table. There will be following PR to address the TODO items in this patch.
In this PR, it creates a array of mp4parser_indice which mimics the structure in gecko [1]. And pass the array point to gecko. So the memory footprint should be very close to stagefright because stagefright also creates its own Indice nsTArray.
There are 2 TODO items, 'elst' and 'ctts', I believe parsing 'elst' is more priority because it has the precise sample composition time.
I also try to make this patch more functional way for a while. But it looks like I probably don't get the point of functional program yet.
[1] http://searchfox.org/mozilla-central/rev/bf98cd4315b5efa1b28831001ad27d54df7bbb68/media/libstagefright/binding/include/mp4_demuxer/Index.h#46

create sample table

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

The package repository now has support for continuous integration
status badges. Add links for these.

Add travis badge link for crates.io.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

This is for https://bugzilla.mozilla.org/show_bug.cgi?id=1339192

Handle trailing bytes in "null-terminated" strings when reading hdlr

---

mp4parse/src/lib.rs

Check ```encv``` box type for protected VP sample entry.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1340980

Add protected box for VP9/8

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

This also refactors read_{audio,video}_sample_entry.

Follow-up to PR #65: add a missing track.codec_type init and add a test

---

mp4parse_capi/src/lib.rs

It causes subtract overflow in u64 [1].
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1342852

convert to i64 before substracting

---

mp4parse/tests/overflow.rs

The library assumes runtime checking of integer arithmetic
overflows, which was much nicer than putting checked_foo()
methods everywhere. We set debug-assertions = true in
Cargo.toml to enable this even for release builds, where
the compiler normally turns it off for performance reasons.
However, it's not clear this is working with rust 1.15.1.
Add a test which checks for the expected panic.

Verify we're compiled with runtime overflow checking.

---

mp4parse/Cargo.toml

This pulls in the dual MIT license for consistency with servo code.

Update bitreader to 0.3.0.

---

mp4parse/tests/overflow.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

These are the simple ones. I've left the `single_match` and `needless_range_loop` issues for now.

Fix some clippy warnings

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse_capi/src/lib.rs

In Gecko, audio codec specific data (descriptor tag 0x05 in ```esds```) is required. PlaformDecoderModule like ffmpeg needs this field to initialize decoder.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1347834

get audio codec specific data

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

In [1], attacker overflows the buffer size to attack FF. To avoid this problem and the possible OOM, we limit the read_buf size to BUF_SIZE_LIMIT which is 1MB now.
This value sounds reasonable right now, we can change it in future if necessary.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1329126

Limit read_buf size to BUF_SIZE_LIMIT in case of overflow problem

---

mp4parse_capi/Cargo.toml
mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs

Use Option<extern fn()> to represent potentially-null function pointer.
This addresses https://bugzilla.mozilla.org/show_bug.cgi?id=1351497, which was filed as a rustc bug in https://github.com/rust-lang/rust/issues/40913, but revealed to be undefined behaviour that happened to work with earlier compiler versions.
As the comment removed in this patch describes, the only reason this code existed was to work around a limitation of rusty-cheddar.
Not sure what to do about the rusty-cheddar issue.  We can patch the generated header manually (by replacing the bogus mp4parse_io member `Option read` with `intptr_t (*read)(uint8_t* buffer, uintptr_t size, void* userdata)` for now, but that's not an ideal solution.

Fix UB caused by casting a Rust fn ptr to a *c_void (BMO bug #1351497)

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

We never store the fields anywhere (and probably never will), so there's no point keeping this code around.  Also, we've had several parse failures in the past where the ambiguous specification of this string type has caused issues.

Remove unused string reading from read_hdlr and read_video_sample_entry.

---

.travis.yml
mp4parse_capi/tests/build_ffi_test.rs

It's easy to forget to `make -C examples check` when making changes that may affect FFI integration, and it's painful to only discover breakage after pushing to GitHub and getting a response from Travis.
It'd be nicer if Cargo had a way to run external scripts so we could build and run these tests explicitly, but adding an integration test that does this is still an improvement over the current situation IMHO.
Longer term this may be addressed by https://github.com/rust-lang/cargo/issues/545.

Build example/test FFI integration test via a Cargo integration test.

---

mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Fragmented file can be recognized from stsc, stco, and stts. There is no requirement to keep empty_sample_boxes anymore.

Remove empty_sample_boxes.

---

mp4parse_capi/src/lib.rs

The codec_specific_data and codec_specific_config are confused when using in gecko layer. We should sync their names same as gecko.
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1358024

Sync codec specific field name as gecko

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1372838. JPEG could be the video track type in QT format. [1]
[1] https://developer.apple.com/library/content/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html

Add JPEG atom for QT

---

mp4parse_capi/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1376190
The ```ctts``` box version 1 could produce a negative time. Since we treat all ```cts``` as version 1, the negative time is expectable.
[1] 14496-12 8.6.1.3.1

Don't reject the negative timecodes.

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1374194
Support AC3/EC3 audio sample entry in QT [1].
[1] https://developer.apple.com/library/content/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-SW1

support ac3, ec3 atom for quicktime format

---

.travis.yml
Cargo.toml
mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml
mp4parse_capi/examples/Makefile

This makes development slightly easier (IMHO) since you can run `cargo test --all` in the top-level instead of having to run the tests in each sub-crate individually.

Add a top-level workspace Cargo.toml.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse_capi/src/lib.rs

This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1380468.
We should check ```samples_per_chunk``` and ```sample_count``` in the parser and return a ```TABLE_TOO_LARGE``` error code.

Check sample count to prevent OOM

---

mp4parse/src/lib.rs

This is from https://bugzilla.mozilla.org/show_bug.cgi?id=1389470. The VM space is 2G in the 32-bit environment which causes OOM when the table size is too large. The original length could use up to 800MB memory that causes OOM very easily.
So this patch reduces table size to one-day long video to avoid OOM.

Reduce max table length in 32bit arch for OOM problem

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

The algorithm to count the descriptor length is incorrect before. (I should get an updated 14496-1 spec. )
[1] https://github.com/crosswalk-project/chromium-crosswalk/blob/master/media/formats/mp4/es_descriptor.cc#L14

Correct descriptor length algorithm

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1387739
```0x06 0xff 0x7f```, the length of tag 0x06 is out of the remain slice boundary.

An invalid descriptor causes an incorrect slice.

---

mp4parse_capi/examples/test.cc

Makes testing files through this interface easier.

Add a `-v` switch to enable logging on the capi test.cc example.

---

mp4parse_capi/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1395244
```
SampleToChunkBox { samples: [
SampleToChunk { first_chunk: 100663297, samples_per_chunk: 2, sample_description_index: 1 }, 
SampleToChunk { first_chunk: 2, samples_per_chunk: 1, sample_description_index: 1 }] }
```
Invalid first_chunk causes an invalid range (100663297, 2) in ```stsc_iter```, so the sample_table doesn't have any item. That causes ```index out of bounds``` error in the bug.
I'll add testcase in gecko gtest.

make sure sample_table length > 0 before using

---

Cargo.toml
fallible/Cargo.toml
fallible/README
fallible/lib.rs
mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Rust doesn't support fallible memory allocation which causes lots of OOM in https://bugzilla.mozilla.org/show_bug.cgi?id=1389470.
In https://bugzilla.mozilla.org/show_bug.cgi?id=1389009, it adds a crate for ```FallibleVec``` which calls the native memory allocation which doubles its capacity and returns a Result.
So in this PR, we call ```FallibleVec.try_push()``` for each mp4 table in case of OOM. Because the memory management could be different between pure rust and the gecko, so we add a function ```mp4parse_fallible_allocation()``` to enable it.
Frankly speaking, it more likes a temporary solution before Rust supports fallible allocation officially in https://github.com/rust-lang/rfcs/pull/2116.

add fallible memory allocation for vector

---

mp4parse/src/lib.rs

In https://github.com/mozilla/mp4parse-rust/pull/114, it needs to allocate memory for ```read_buf()```; however, it just extends its capacity, its length stays zero. So we need to initialize it to correct its length. Otherwise, it returns error in
```
impl Read for mp4parse_io {
fn read(&mut self, buf: &mut [u8]) {
...
let rv = self.read.unwrap()(buf.as_mut_ptr(), buf.len(), self.userdata);
if rv >= 0 {
Ok(rv as usize)
```

initialize the read buffer

---

mp4parse_fallible/lib.rs

This fixes a bug where try_reserve(0) would call malloc(0) then construct a Vec via from_raw_parts with the valid resulting 0-sized allocation and a capacity of 0.  Rust's implementation of Vec (specifically in RawVec::dealloc_buffer and RawVec::current_layout) assumes that a 0-capacity RawVec never allocated so avoids calling dealloc in this case.
r? @alfredoyang

Don't (re)allocate if the new_cap is the same size as old_cap.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse_capi/Cargo.toml

In https://github.com/mozilla/mp4parse-rust/pull/118, it's wrong to use 'feature'.
This PR also depresses the 'unreachable_code' warning when 'mp4parse_fallible' is enabled.

Fix wrong feature usage in previous PR 

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1393045
ffmpeg generates such kind of audio samples. Its spec is at https://developer.apple.com/library/content/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-BBCGEBEH "Sound Sample Description (Version 2)".

support audio sample entry v2

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs

In https://github.com/mozilla/mp4parse-rust/pull/124, it added 'chan' box when parsing 'lpcm' audio entry.  But 'chan' box could exist with other codec types, so we remove it from codes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1415807

'chan' box could exist in other audio entry.

---

mp4parse_capi/examples/Makefile
mp4parse_capi/tests/build_ffi_test.rs

Fix failing build_ffi test under current nightly after rust-lang/rust#43067 landed.
rustc no longer prints the list of libraries for the linker by default, they must be requested with --print native-static-libs.  To make life interesting, that flag is incompatible with the current stable rustc, so we need to handle both cases for now.
This fixes the failing CI builds such as https://travis-ci.org/mozilla/mp4parse-rust/jobs/302161109

Fix failing build_ffi test under current nightly after rust-lang/rust#43067 landed.

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

Keep the release version in sync with the capi crate, but the
minor bump is also warranted by api changes.

Bump mp4parse version to 0.9.0 for release.

---

mp4parse/Cargo.toml

Now that this crate is available on crates.io, refer
to a stable version rather than building against a
git master branch.

Refer to the published version of mp4parse_fallible.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs

https://users.rust-lang.org/t/announcing-afl-rs-0-2-bindings-for-american-fuzzy-lop/13981
afl.rs no longer requires unstable Rust and also doesn't need a compiler
plugin.

Bump afl.rs integration to reflect latest changes.

---

mp4parse_capi/Cargo.toml

This makes us depend on serde 1.0, just like everyone else in the ecosystem.

Switch to cbindgen 0.3

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

There is an extra byte at the end of ```esds```, in the original design, it runs into io error when reading data. That's an invalid descriptor frankly speaking, but it is good if we could tolerate this kind of error and keep parsing instead of returning an error.
the whole esds:
```[3, 25, 0, 1, 0, 4, 19, 64, 21, 0, 0, 0, 0, 0, 0, 0, 0, 1, 119, 0, 5, 2, 18, 16, 6, 1, 2]```
es descritor within esds:
```[4, 19, 64, 21, 0, 0, 0, 0, 0, 0, 0, 0, 1, 119, 0, 5, 2, 18, 16, 6, 1, 2]```
dc descriptor within es:
```[5, 2, 18, 16, 6, 1]```
The final ```2``` is redundant data.
https://bugzilla.mozilla.org/show_bug.cgi?id=1426773

check descriptor length before parsing

---

mp4parse_capi/src/lib.rs

Remove `free_null_parser` test which incorrectly relied on panic! unwinding an FFI function.
Closes #136.

Remove `free_null_parser` test which incorrectly relied on panic! unwinding an FFI function.

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

The compatibility encoding is not supported as I can't find any files encoded that way. See the bottom of https://github.com/macosforge/alac/blob/master/ALACMagicCookieDescription.txt for a description.
Closes #57

Support alac (Apple lossless audio codec)

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/examples/dump.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs

Remove callers of `mp4parse_log` in favour of `env_logger`.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Also remove `mp4parse_log` from the C API, since the logging is now controlled externally via the host application's specified `Log` impl.
This also effectively addresses issue #140 since *everything* is moved to `debug!` output.

Replace custom log! macro with standard log crate.  Closes #139.

---

mp4parse_capi/Cargo.toml

When we switched to the `log` crate from our own custom logging
in v0.10, I added `env_logger` as an implementation so our code
examples would continue to work the same way.
However, since `env_logger` is _only_ needed for example code
is should be declared as a dev-dependency so it doesn't add
a transitive dependency to other builds using the library,
which may use a different logging implementation, or a just
a different version of `env_logger` than the one we've declared.

Move env_logger to dev-dependencies.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

Two issues:
1- MP4 contained 3 entries in the edit list, which the code error-ed on (ignore that error, and while at it, ignored all error
2- That particular mp4 contains rubbish data after the entries (like many mp4 that pre-allocate space before writing content in order to do everything in one pass). So we skip it

Fix bug 1455701

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs

This allow parsing 'uuid' boxes.
While this is generic to the ISO Base Media format, I implemented this to be able to parse Canon CR3 files (brand 'crx ') that use 'uuid' boxes.

Parse uuid box types

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

Per https://bugzilla.mozilla.org/show_bug.cgi?id=1457359#c6
@jyavenard r?

Ignore truncated uuid boxes rather than raising an error.

---

mp4parse/src/lib.rs
mp4parse/src/macros.rs
mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/examples/dump.rs
mp4parse_capi/src/lib.rs

- Recognize metadata tracks: they can matter.
- Move check_parser_state macro to boxes.rs so that it can be used by another module.
The purpose of these is to facilitate my fork that I use to parse Canon CR3 files. These changes are generic to the IsoBaseMedia.

Misc improvements

---

.travis.yml

Enable further operating systems on Travis to get more coverage. Since we don't run make and gcc on Windows we don't need any special installs outside of the default Rust env. OSX requires a little tweaking, but also works.
Windows support is new to Travis, but given we're not doing anything too exotic, should hopefully be safe.

Enable osx and win travis

---

README.md

As I've been learning about the crate(s) I've been collecting some of the high level details in the README. I figure this kind of high level overview would be useful for others unfamiliar with the project.

Expand README.md to provide details on project structure

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/examples/afl-capi.rs
mp4parse_capi/examples/dump.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs

The mp4 spec allows for tracks to have multiple sample descriptions.
This is done to allow for different codings within a track. Cases of
this being done appear to be rare, and historically the parser was able
to assume a single description was used. However, instances of multiple
descriptions are appearring in encrypted content packaged by Google's
Shaka packager. To avoid compatibility issues, and as this behaviour is
specified, we should handle and expose multiple samples descriptions per
track.
Technically, this changes how we expose the contents of stsd boxes.
Previouslly we would map a combination of the contained entires to a
single `data` member of the associated track. With this change, a track
now exposes each of its sample descriptions. The data member on tracks
has been …

 Handle and expose multiple sample descriptions per track

---

mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_sample_table.rs

- There are a number of cases where structs that have default values are
being created with explicit values in the capi tests. We can just use
default(), it makes the tests more concise, and avoids confusion where
readers may think we're intentionally using explicit values for
programatic reasons.
- Recent changes have moved codec information from track structures to
sample description structures -- as a single track may have multiple
different sample descriptions with their own codecs. In doing so, I had
removed some codec checks from our tests. Restore some of these checks
in test_fragment.rs, so that we have coverage, and as that test inspects
at the sample description level.

capi tests: use default() for structs and add back some codec checks.

---

.travis.yml

Per [this](https://changelog.travis-ci.com/oclint-is-removed-from-mac-builds-79270) we no longer need the work around for travis, and indeed need it removed to avoid failures.
Edit: should it be useful, see also https://github.com/travis-ci/travis-ci/issues/8826 for historical context.

Remove oclint work around for travis now that it's not needed.

---

mp4parse/Cargo.toml
mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_encryption.rs

The SchemeType box stores a four character code representing the
encryption scheme used for a track. It also stores a version number for
the scheme used. Historically the scheme could be determined by other
metadata, without explicitly reading the FourCC. This appears to still be
the case, however, parsing this information is useful because:
- It's easier to read the encryption scheme from the scheme type box
that deduce it from other values.
- We can use the explicit scheme type to checksum the other encryption
values and make sure they're sane for a given type.
- If I'm wrong about being able to deduce all schemes from other
metadata, we may require the scheme type to handle certain encrypted
media.
The scheme type is read and exposed in both the rust and C APIs. The
scheme version is …

Handle schm box

---

mp4parse/src/lib.rs

Zero initialize Vec returned from mp4parse_fallible branch of allocate_read_buf.
Also delete vec_reserve, which is completely unused.
Closes #172.
r? @SingingTree please

Zero initialize Vec returned from mp4parse_fallible branch of allocate_read_buf.

---

mp4parse/src/lib.rs

"..=" has been stable since early 2018, so it's safe to use.
r? @SingingTree please

Switch to newer "..=" inclusive range syntax to avoid deprecation warnings on Nightly.

---

mp4parse_capi/src/lib.rs

Add documentation to
- Help others understand the code.
- Make sure I understand these members correctly before I submit further PRs.

Add documentation for the members of Mp4parseIndice.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs

Seeks to fix https://github.com/mozilla/mp4parse-rust/issues/176 and add some more documentation along the way.
Let me know if some other formatting is preferred for the multilines that were broken. I based this on rustfmt's defaults.

Update vpx config box names

---

mp4parse_capi/src/lib.rs

This fixes clippy lints that show up in nightly that I'd overlooked in https://github.com/mozilla/mp4parse-rust/pull/185
This is largely adding safety sections to the unsafe pub functions on the capi. These are largely similar in that the functions are dereferencing raw pointers, so the callers need to provide sane pointers.
There is one additional case of using `map` instead of `and_then` on an optional to avoid rewrapping a `Some`.

Fix clippy lint warnings from nightly version of clippy.

---

mp4parse/src/tests.rs

Fix some trailing white space I left in while linting.

Remove a trailing whitespace from mp4parse tests.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs

Add `to_u64` and `to_usize` trait functions for infallible conversions
which can be checked at compile time to be platform safe.
Additionally, convert some arithmetic to checked versions so we can
error rather than panic or give invalid results on overflow.
Remove some unnecessary trait bounds on struct definitions.
Update `skip` to avoid allocating a buffer.

Replace casts with infallible or error-checked conversions

---

mp4parse_capi/src/lib.rs

This was changed by rustfmt, but it breaks `build_ffi_test` for some reason.
Add annotation to keep rustfmt from reordering them again (at least until we
come up with a better fix).
See https://github.com/mozilla/mp4parse-rust/issues/197#issuecomment-596910016

Fix CI by undoing the reordering of extern crate statements

---

mp4parse/src/lib.rs

This improves the runtime of the public_avif_read_samples test from >20s to
<0.3s.  In optimized builds, there's no performance issue with
Iterator::flatten, so the runtime of both versions are the same.

read_avif: Collapse primary_items_extents_data with Vec::concat instead of Iterator::flatten.

---

mp4parse_capi/examples/dump.rs
mp4parse_capi/examples/test.cc
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_chunk_out_of_range.rs
mp4parse_capi/tests/test_encryption.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs
mp4parse_capi/tests/test_workaround_stsc.rs

https://github.com/mozilla/mp4parse-rust/pull/200#discussion_r390008980 was a good suggestion; I just didn't see it before merging https://github.com/mozilla/mp4parse-rust/pull/200, so here it is.
The Mp4parseParser is now set through an output parameter. Returning a status
is more consistent with the rest of the API and results in somewhat simpler code.
Equivalent changes for mp4parse_avif_new as well.

Refactor mp4parse_new to return Mp4parseStatus

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

See https://github.com/mozilla/mp4parse-rust/issues/204
It's too easy to accidentally call functions in `Vec` which may allocate, so
rather than relying on the consumer to use `vec_push` instead of `Vec::push`
and the like, make `TryVec` a thin wrapper around `Vec`, which will return
`Result`s for all the operations which allocate and will use fallible allocation
when the `mp4parse_fallible` feature is enabled.
For now, as a proof of concept, only replace `Vec`s the newly-added AVIF
code. If this works well, expanding to the rest of the code shouldn't be
too much additional effort.

Switch Vec to TryVec for fallible allocation

---

mp4parse_capi/src/lib.rs

This is a fairly minimal fix to unblock fuzz testing. I'll follow up with
a more general fix by wrapping these types and only allowing checked
arithmetic.
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24883

Return error for overflow in create_sample_table

---

mp4parse/src/lib.rs

This fixes https://oss-fuzz.com/testcase-detail/5637965842481152. We were timing out due to the additional time it takes to do many small allocations.

When reading ftyp preallocate the memory to hold all the brands

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml
mp4parse_capi/src/lib.rs

See https://bugzilla.mozilla.org/show_bug.cgi?id=1660551#c3
This appears related to https://github.com/rust-lang/rust/issues/61002
though, I'm not sure what changed between versions of num-traits to make
this an issue, pinning to the version we were already using seems to
function as a workaround for now.

Fix bustage from BMO bug 1660551

---

mp4parse/src/boxes.rs
mp4parse/src/fallible.rs
mp4parse/src/lib.rs

Using `{:?}` inside `Debug::fmt` implementation loses formatter flags, e.g. breaks `{:#?}` formatting.
I've also simplified other debug implementations where `write!` formatting machinery was unnecessary for printing a single string.

Improve debug format implementations

---

mp4parse/src/lib.rs

This fixes a timeout with [the attached testcase](https://github.com/mozilla/mp4parse-rust/files/5491742/clusterfuzz-testcase-minimized-avif-5139142796902400.zip) run against the `mp4parse_capi` crate with:
```
cargo +nightly fuzz run avif clusterfuzz-testcase-minimized-avif-5139142796902400 -- -timeout=60
```
Resolves https://oss-fuzz.com/testcase-detail/5139142796902400

Check ipma validity and preallocate associations vec

---

mp4parse/Cargo.toml
mp4parse/benches/avif_benchmark.rs

Run it with `cargo bench`
See https://bheisler.github.io/criterion.rs/book/index.html for more

Add a benchmark for measuring AVIF parsing performance

---

mp4parse/src/lib.rs

Resolves https://oss-fuzz.com/testcase-detail/5107469717864448
This fixes a timeout with the [attached testcase](https://github.com/mozilla/mp4parse-rust/files/5528015/clusterfuzz-testcase-minimized-avif-5107469717864448.zip) run against the mp4parse_capi crate with:
cargo +nightly fuzz run avif clusterfuzz-testcase-minimized-avif-5107469717864448 -- -timeout=60

Add check for required explicit extent offset and length in iloc

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/tests/public.rs

This fixes a timeout with [the attached testcase](https://github.com/mozilla/mp4parse-rust/files/5539940/clusterfuzz-testcase-avif-5641604844748800.zip) run against the `mp4parse_capi` crate with:
```
cargo +nightly fuzz run avif clusterfuzz-testcase-avif-5641604844748800 -- -timeout=6
```
Resolves https://oss-fuzz.com/testcase-detail/5641604844748800

Preallocate storage when parsing iref box and add debugging output

---

mp4parse/benches/avif_benchmark.rs
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

This simplifies the caller by eliminating the need to create the context, ensures that an empty/invalid context doesn't exist to accidentally operate on, and makes the code more idiomatic rust.
Also, make some other minor cleanups.

Make parsers return context objects rather that using out params

---

mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/src/lib.rs

When they're already contiguously present in an `mdat` buffer (even the same one), `AvifContext::primary_item()` and `::alpha_item()` can return slices rather than having to copy the (potentially large) buffers.
This results in a measured performance increase of ~50% for parsing a 4.7 MB AVIF (the largest in our test set):
```
$ git checkout master
$ cargo bench -- --save-baseline base
avif_largest            time:   [2.0990 ms 2.1352 ms 2.1727 ms]
```
```
$ git checkout avif-nocopy
$ cargo bench -- --save-baseline avif-nocopy
$ cargo bench -- --load-baseline avif-nocopy --baseline base
avif_largest            time:   [1.0077 ms 1.0257 ms 1.0449 ms]
change: [-52.649% -51.371% -50.022%] (p = 0.00 < 0.05)
Performance has improved.
```
Also, clean up some related code add add tests.

Avoid unnecessary copies of AVIF primary_item and alpha_item

---

mp4parse/src/lib.rs

Resolves https://oss-fuzz.com/testcase-detail/5639655386775552
This fixes an assert with the [attached testcase](https://github.com/mozilla/mp4parse-rust/files/5626321/clusterfuzz-testcase-minimized-avif-5639655386775552.avif.zip) run against the mp4parse_capi crate with:
```
cargo +nightly fuzz run avif clusterfuzz-testcase-minimized-avif-5639655386775552.avif -- -timeout=6
```

Return error if iloc box contains duplicate item_ID

---

mp4parse/src/lib.rs

Resolves https://oss-fuzz.com/testcase-detail/5990897275764736
This fixes an assert with the [attached testcase](https://github.com/mozilla/mp4parse-rust/files/5647901/clusterfuzz-testcase-minimized-avif-5990897275764736.zip) run against the mp4parse_capi crate with:
```
cargo +nightly fuzz run avif testcase-minimized-avif-5990897275764736 -- -timeout=6
```

Check for overflow when calculating ipma index

---

mp4parse_capi/fuzz/fuzz_targets/avif.rs
mp4parse_capi/src/lib.rs

Create an API to expose the `alpha_item` and `premultiplied_alpha` with `Mp4parseAvifParser`. This helps to add the alpha support in [BMO1654462](https://bugzilla.mozilla.org/show_bug.cgi?id=1654462)

Add an API exposing alpha_item and premultiplied_alpha

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

The latter is required by https://github.com/image-rs/image/pull/1398

Bump env_logger and num-traits

---

mp4parse/tests/public.rs
mp4parse_capi/tests/test_encryption.rs

Since these allow lines were added, this clippy lint has been downgraded
to a nursery check via
https://github.com/rust-lang/rust-clippy/pull/5428
Since we don't have allows for other nursery lints, I suggest we remove
these ones.

Remove lines allowing clippy cognitive complexity checks.

---

mp4parse_capi/examples/dump.rs
mp4parse_capi/src/lib.rs

Also, improve logging generally. This allows for a simple test of either an AVIF or other MP4 to analyze the parsing behavior or see what sort of error causes a failure.

Add support for AVIF to `dump` example command

---

mp4parse/src/boxes.rs

This is useful for making entries feature gated like so:
```rust
box_database!(
// …
MP4VideoSampleEntry               0x6d70_3476, // "mp4v"
#[cfg(feature = "3gpp")]
AMRNBSampleEntry                  0x7361_6d72, // "samr" - AMR narrow-band
// …
);
```
Also, move the `fmt::Debug` impl for `BoxType` outside the macro, since it doesn't depend on any of the macro parameters.

Allow optional attributes on entries in the box_database macro

---

mp4parse/src/lib.rs

Resolves https://github.com/mozilla/mp4parse-rust/issues/274
See also https://bugzilla.mozilla.org/show_bug.cgi?id=986926. When we update mp4parse_capi in mozilla-central, we're going to have to address [one issue from a previous commit](https://github.com/mozilla/mp4parse-rust/pull/245#issuecomment-778692532), but that should be straightforward, I think.

Add support for MPEG-2 layer 3 codec ID

---

.github/workflows/build.yml

This GitHub Action replicates the existing Travis config, except I restricted the nightly builds to debug-only for simplicity/economy.  There's a bit of duplication compared to the Travis config, I hope that can be improved over time.
@baumanj I know you were investigating CircleCI for this repository.  If you'd prefer to use that, I don't mind - I've been working with Actions for the cubeb repositories and it was easy to put something together for mp4parse based on that, so I thought I'd put it up for review and leave it up to you.

Add build action.

---

.github/workflows/build.yml
mp4parse/benches/avif_benchmark.rs
mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Inspired by https://github.com/mozilla/mp4parse-rust/pull/186, updated for GitHub Actions.
Running a separate step for nightly clippy is annoying, but non-nightly builds don't recognize `clippy::upper_case_acronyms` and as far as I understand it's not currently possible to disable lints via Cargo.toml or clippy.toml.

Add clippy to build action.

---

mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_encryption.rs

This fixes the following warning:
warning: name `OptionalFourCC` contains a capitalized acronym
--> mp4parse_capi/src/lib.rs:331:10
|
331 | pub enum OptionalFourCC {
|          ^^^^^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter (notice the capitalization): `OptionalFourCc`
|
= note: `#[warn(clippy::upper_case_acronyms)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

clippy: Rename OptionalFourCC -> OptionalFourCc

---

.github/workflows/build.yml

This should make our standard GitHub Actions CI run every day at 10am UTC (as well as on pushes and PRs).
Inspired by https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events

Run CI every day

---

mp4parse/Cargo.toml
mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/cbindgen.toml

This PR adds support for XML and Binary XML metadata boxes. 
They can be found for example in files coming from Sony cameras. 
Sample file here: https://drive.google.com/file/d/1EpOzytKGmx7YyKdmZW1_8b4pMHCVNGrs/view?usp=sharing

Add support for XML metadata box

---

mp4parse/src/lib.rs
mp4parse_capi/src/lib.rs

Change Mp4parseByteData.length to usize, eliminating unsafe casts

---

mp4parse/src/lib.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#cmp_owned
Surfaced by https://github.com/mozilla/mp4parse-rust/runs/2443009191

Fix clippy::cmp-owned on impl_bounded_product

---

mp4parse/src/lib.rs

```
error: this expression borrows a reference (`&Extent`) that is immediately dereferenced by the compiler
--> mp4parse/src/lib.rs:907:51
|
907 |                     if let Some(slice) = mdat.get(&extent) {
|                                                   ^^^^^^^ help: change this to: `extent`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
```

Fix clippy needless-borrow lint

---

mp4parse_capi/Cargo.toml

There's no good reason `mp4parse` and `mp4parse_capi` should be using different versions

Use the same version of fallible_collections

---

.github/workflows/build.yml

Without failing the whole run, it's hard to notice when we get failures in nightly, but nightly should be the advance notice that we pay attention to.

Fail actions run for nightly failures

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

See https://github.com/mozilla/mp4parse-rust/issues/308

Make hdlr box parsing reject invalid input according to ParseStrictness

---

mp4parse/LICENSE
mp4parse/README.md
mp4parse_capi/LICENSE
mp4parse_capi/README.md

The LICENSE file is an identical copy of the one at the top level of the repo
The individual README.md files refer back to the top level one
Resolves https://github.com/mozilla/mp4parse-rust/issues/313

Add LICENSE and README.md to individual crate directories

---

mp4parse/src/boxes.rs

The current code causes a lint error in CI (https://github.com/mozilla/mp4parse-rust/actions/runs/1074468202):
```
error: unused attribute `deny`
--> mp4parse/src/boxes.rs:101:1
|
101 | #[deny(unreachable_patterns)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D unused-attributes` implied by `-D warnings`
note: the built-in attribute `deny` will be ignored, since it's applied to the macro invocation `box_database`
--> mp4parse/src/boxes.rs:102:1
|
102 | box_database!(
| ^^^^^^^^^^^^
```
Since this lint is already globally enabled as a warning, and our CI uses the ` -D warnings` option, this check will already be enabled as a CI fatal error

Remove #[deny(unreachable_patterns)]

---

mp4parse/Cargo.toml

Requiring hashbrown = v0.11 ends up causing hashbrown to be built twice. Once for mp4parse and and v0.9 for faillable-collections. hashbrown doesn't appear directly used by mp4parse, so we can just drop the requirement on v0.11.

Drop unused and duplicated dependency on hashbrown

---

.github/workflows/build.yml
mp4parse/src/lib.rs

This was present in the travis configuration that was removed in https://github.com/mozilla/mp4parse-rust/commit/f3c5f88d93da28c6c6dcd6d352d5ba9baab3b354. It remains useful since it can catch errors in the rustdoc such as in https://travis-ci.org/github/mozilla/mp4parse-rust/jobs/774702058

Add `cargo doc` to CI

---

.github/workflows/build.yml
mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml

Currently the `PixelInformationProperty` (`pixi`) box defined in HEIF (ISO 23008-12:2017) § 6.5.6 is required to be present per MIAF (ISO/IEC 23000-22:2019) specification § 7.3.6.6:
> The pixel information property shall be associated with every image that is displayable (not hidden) 
However due to a bug ([now fixed](https://github.com/strukturag/libheif/commit/f8e2306c8f803fc158e6decb32ff1c78d1f7eef8)) in [libheif](https://github.com/strukturag/libheif), AVIF images lacking this property were created and may remain in the wild. After receiving https://bugs.chromium.org/p/chromium/issues/detail?id=1198455, Chrome relaxed their check for this requirement and it is unclear whether it will be reinstated.
Discussion is underway to modify MIAF to allow the pixi property to be omitted, but …

Add "missing-pixi-permitted" feature

---

.github/workflows/build.yml

I checked this worked by intentionally re-introducing a warning for this run: https://github.com/mozilla/mp4parse-rust/runs/3366215594
It's now been reverted and everything should be green.

Run clippy on fuzzer code

---

mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

This is required for https://bugzilla.mozilla.org/show_bug.cgi?id=1696045, so that we can record telemetry on whether the `pixi` box is present

Expose the pixel information (pixi) via the C API

---

mp4parse/src/lib.rs

https://github.com/rust-lang/rust-clippy/issues/6727 has been fixed, so this is no longer necessary

Remove obsolete clippy::wrong_self_convention

---

mp4parse_capi/examples/dump.rs
mp4parse_capi/fuzz/fuzz_targets/avif.rs
mp4parse_capi/fuzz/fuzz_targets/mp4.rs
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_chunk_out_of_range.rs
mp4parse_capi/tests/test_encryption.rs
mp4parse_capi/tests/test_fragment.rs
mp4parse_capi/tests/test_rotation.rs
mp4parse_capi/tests/test_sample_table.rs
mp4parse_capi/tests/test_workaround_stsc.rs

and consequently some `unused-mut` warnings
Identified by scheduled CI in https://github.com/mozilla/mp4parse-rust/runs/3754585345

Fix `clippy::needless-borrow`

---

mp4parse/src/lib.rs

I double-checked these are still to the correct sections in the 2020 version and fixed up a couple typos

Update ISOBMFF references to 2020 version

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

While our new release strategy will start with v0.12.95 around December 7th with the changes in https://github.com/mozilla/mp4parse-rust/pull/347, I didn't want to make https://github.com/mozilla/mp4parse-rust/issues/339 wait so long to be resolved. This will allow for an updated release which is not in sync with any particular Firefox version.

Bump version to 0.11.6 for new release

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

Object types sourced from https://mp4ra.org/#/object_types.
This addresses [BMO 1722497](https://bugzilla.mozilla.org/show_bug.cgi?id=1722497).  I included `0x66` as well, since that's listed in the above reference as another (uncommon) AAC object type.
Curiously, the `0x41` object type we've accepted since this code was first added isn't listed.  I'm not sure where that value came from.

Recognize ISO 13818-7 MPEG-2 object types for AAC.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml

This create already won't work with 2015-only versions of Rust, so it may as well update to a newer edition.

Upgrade to 2018 edition

---

mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/src/unstable.rs
mp4parse_capi/src/lib.rs

This should fix the build failures on CI.

Fix `unstable-name-collisions` warning by using fully qualified path.

---

mp4parse/Cargo.toml
mp4parse/src/boxes.rs
mp4parse/src/lib.rs
mp4parse/tests/public.rs
mp4parse_capi/Cargo.toml
mp4parse_capi/examples/dump.rs
mp4parse_capi/src/lib.rs

All properties not related to the `pitm` box have been moved from mp4parse_avif_get_image to mp4parse_avif_get_info. New fields for the color and alpha tracks are included in Mp4parseAvifInfo. To get the sample indices for those tracks, mp4parse_avif_get_indice_table was added as well.
These changes break C API backwards compatibility due to removing fields from Mp4parseAvifImage, so the version is bumped to 0.16.0.
I've implemented AVIF sequence decoding into Firefox using these changes, so they have been tested a bit at least. However, it's worth noting that I don't have access to the MIAF spec due to the price to buy it, so if anyone is able to confirm that anything related to that spec is sane that would be great.
I've also added the `pict` and `auxv` track handlers, which could …

Add some support for AVIF sequences.

---

mp4parse/Cargo.toml
mp4parse/src/lib.rs

Libraries are not meant to initialize env_logger themselves.

Remove env_logger dependency.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs

`name` should be truncated after the first nul but we don't store the `name` field so this change just lifts the restriction on multiple nul bytes.
This reflects the spec clarification accepted in https://github.com/MPEGGroup/FileFormat/issues/35

Permit multiple nuls in `hdlr` box `name` field.

---

mp4parse/src/lib.rs
mp4parse/tests/public.rs

The test file with no `pitm` and no `iloc` boxes should have had a loop count of 0 due to their `elst` box flags being set to 0, but the looping field that was read was being skipped due to the empty edit list.
Note: these test files had to be modified manually using MP4Box in gpac, libavif will not write files with no edits.

Read the looping flag when `elst` box is empty.

---

mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_fragment.rs

I missed it was in a different timescale as the tracks, and wasn't exposed elsewhere in the API. This is essentially a revert of part of an earlier patch and adds a member to the fragment info struct.

Expose the mvhd timescale when getting the fragment duration

---

.github/workflows/build.yml

The macos-10.15 target has been deprecated and removed from github, per https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
This updates the build target so to instead tartget macos-12. I've opted to target an explicit version as that's what's done for the other OS targets, rather than using `latest`.

Fix broken build on MacOS

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs

This addresses [BMO 1867424](https://bugzilla.mozilla.org/show_bug.cgi?id=1867424), where the linked media contains an unusual `mvhd` with 2 bytes of trailing data.  Since `mvhd` has a fixed set of fields, we were expecting the `mvhd` size to match the spec based on the size of the known fields (108 bytes for this v0 file, v1 would be larger due to 64-bit fields) but the `mvhd` box size is 110 bytes in this file.  To address this, we now skip the remaining unknown bytes based on the box's reported size.

Ignore unused trailing data in `mvhd`.

---

mp4parse_capi/examples/dump.rs

This fixes the CI error that's been failing on nightly since Feb 19:
```
error: the item `ParseStrictness` is imported redundantly
--> mp4parse_capi\examples\dump.rs:2:5
|
2 | use mp4parse::ParseStrictness;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^
3 | use mp4parse_capi::*;
|     ---------------- the item `ParseStrictness` is already imported here
|
= note: `-D unused-imports` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_imports)]`
```
I tested locally on with both stable and nightly on macOS.

Fix import error in dump.rs

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/overflow.rs
mp4parse_capi/src/lib.rs
mp4parse_capi/tests/test_avis.rs
mp4parse_capi/tests/test_sample_table.rs

See https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants
Hopefully this fixes https://github.com/mozilla/mp4parse-rust/actions/runs/8598206617/job/23558557224
I couldn't reproduce it locally, but the fix didn't seem to break either stable or nightly locally either, so I figure if this passes CI, it should fix the issue.

Fix `clippy::legacy_numeric_constants` lint on nightly

---

mp4parse/Cargo.toml
mp4parse_capi/Cargo.toml

This is a near-duplicate of https://github.com/mozilla/mp4parse-rust/pull/421, but it updates *both* `fallible_collections` dependencies.
I confirmed that `cargo test --workspace` still succeeds.

Update fallible_collections from 0.4 to 0.5

---

mp4parse/src/lib.rs

using `is_none_or` causes [a build error](https://treeherder.mozilla.org/logviewer?job_id=493126982&repo=try&lineNumber=81467) on Linux, full push can be seen [here](https://treeherder.mozilla.org/jobs?repo=try&revision=e2ee1d91178aef400be793bb2a648aa43de36b30&selectedTaskRun=KcQZQi2nTQyGM9yTAIECkw.0).

fallback to 'map_or' to fix Linux build error.

---

mp4parse/src/lib.rs
mp4parse/src/tests.rs
mp4parse/tests/public.rs
mp4parse_capi/src/lib.rs

This is a fix for [BMO# 1936124](https://bugzilla.mozilla.org/show_bug.cgi?id=1936124).

Allow multiple DecoderSpecificInfo entries in non-strict mode

---

mp4parse/src/lib.rs

This is a fix for [BMO# 1925224](https://bugzilla.mozilla.org/show_bug.cgi?id=1925224).

Allow truncated DECODER_SPECIFIC_TAG entries in non-strict mode
